apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka-server
  name: eureka-server
  namespace: cn202009
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - image: harbor.edu.cn/cn202009/eureka-server:{VERSION}
        imagePullPolicy: IfNotPresent
        name: eureka-server
      restartPolicy: Always
	  imagePullSecrets:
	  - name: mytoken
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-server
  name: eureka-server
  namespace: cn202009
spec:
  ports:
  - name: tcp
    nodePort: 32575
    port: 8969
    protocol: TCP
    targetPort: 8969
  selector:
    app: eureka-server
  type: NodePort
